host = "127.0.0.1"
port = 8080

[gitlab]
protocol = "http"
host = "10.30.30.22"
token = "xxxxxxx"

[gitlab.project]

[gitlab.project.11]
branch = "master"
merge_request = [
    "cron://develop/ 0 30 11,17 ? * MON,TUE,WED,THU,FRI *"
]